### ISSUE TITLE
Asset Share Commons Share And Download buttons not functioning

### ISSUE THREAD

**Issue by Shubhankar-Kumar-1** [adobe/asset-share-commons#717] opened 2022-04-28 14:30 UTC
We are using Asset share commons 2.1.12 version.....we were using the share and download modals that are present but we are not able to make them work.

We believe it to be an error in the UrlImpl.java file present at the location "asset-share-commons-asset-share-commons-2.1.12\asset-share-commons-asset-share-commons-2.1.12\core\src\main\java\com\adobe\aem\commons\assetshare\content\properties\impl" as this the error that is getting thrown when we use the button.

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/104577341/165775104-bf3f3afc-a6d2-4cc7-adf8-4e950433e019.png)

Can you please help us with this issue?

**Comment by davidjgonzalez** [comment] 2022-04-28 23:29
Is this happening for every asset? If only certain ones, can you provide the path (or even better a package of an asset that doesn't work)?

Thanks!

**Comment by Shubhankar-Kumar-1** [comment] 2022-04-29 00:56
This is happening for every asset from what we can see....

**Comment by Shubhankar-Kumar-1** [comment] 2022-04-29 01:14
path from where we try to download: "/content/dcx-mediaplace/asc/en/home/category-page/subcategoryList/subcategoryResult.html".

Asset path example: "/content/dam/multisite/multi-brand/parts/na/multi-country/images/complementary/online-complementary/12499/1234-PIC31.jpg".

**Comment by davidjgonzalez** [comment] 2022-04-29 16:27
@Shubhankar-Kumar-1 - 

What version of AEM are you one?

So it looks like the problem is the Path computed property is not active, thus not injected, thus null.

https://github.com/adobe/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/UrlImpl.java#L74

Can you check in /system/console/components what the OSGI component registration for PathImpl looks like?

`com.adobe.aem.commons.assetshare.content.properties.impl.PathImpl`


![2022-04-29 at 12 26 PM](https://user-images.githubusercontent.com/1451868/165985274-4355f020-ecb9-4580-bedc-379bbc6f7a5d.jpg)

**Comment by Shubhankar-Kumar-1** [comment] 2022-04-29 16:45
![image](https://user-images.githubusercontent.com/104577341/165987951-823e6e5f-90bd-419f-b3f8-638c89623b2a.png)


this is the component status in our aem

**Comment by Shubhankar-Kumar-1** [comment] 2022-05-02 10:40
I would kindly request you to help us on this matter as we are not able to fix this issue and the code is already in production...this will get escalated on our side if we don't fix this soon. We can also connect if required for this matter.

**Comment by davidjgonzalez** [comment] 2022-05-02 16:51
Hi @Shubhankar-Kumar-1  - sorry, I cannot reproduce this w/ 2.1.12 on 6.5.11 -- this all works fine for me.  So I don't know how to help you. I suggest you try reproducing this on a vanilla AEM 6.5 SP11 with vanilla ASC 2.1.12 (or even better, you should be using 2.2.0)

The exception you provided doesn't make sense since from what i can tell the only thing i can see on that line that would cause a NPE is if the PathImpl OSGi component is not active, which you show as active in the previous screenshot.

Maybe you can download ASC source code (using git tag for 2.1.12) and hook up a remote debugger to your local that is exhibiting this to understand whats going on in your AEM better.

**Comment by davidjgonzalez** [comment] 2022-09-14 01:40
Closing. Please re-open of you need more help.

**Closed by davidjgonzalez** 2022-09-14 01:40 UTC
Labels: bug, needs more info
