### ISSUE TITLE
Thumbnail missing for .oft files in Asset Share Commons

### ISSUE THREAD

**Issue by RahulMohann** [adobe/asset-share-commons#1154] opened 2024-07-08 13:25 UTC
Hi,

For the .oft files, thumbnails are not displaying in asset share commons (search page). We also had a similar concern with zip files. But then we added a static rendition (cq5dam.thumbnail.319.319.png) to the zip asset in the author (with the help of a post-processing workflow), and then it worked in the ASC. We are trying to do the same for .oft assets as well, but not working. Means, even though the static rendition (cq5dam.thumbnail.319.319.png) is added to the asset, it's not displaying in ASC. I've compared the changes (workflow, dispatcher, etc.) with what we have done for Zip and everything looks the same. The only difference I see is the fileType/mime type. Oft files are getting added as "image/png" in the author, whereas zip is added as "application/zip". Not sure if that has something to do here. Could you please advise on how we can fix this?
@davidjgonzalez 

Thanks,
Rahul

**Comment by davidjgonzalez** [comment] 2024-07-08 14:00
What version of ASC and AEM? I this on AEM as a Cloud Service (on true cloud?)

**Comment by Robedean** [comment] 2024-07-08 18:18
@davidjgonzalez  - adding that we made custom .png thumbnails for the .oft files. These thumbnails display in AEM Assets, but not on ASC.

**Comment by RahulMohann** [comment] 2024-07-11 14:35
Hello @davidjgonzalez , Any clue on this?

**Comment by RahulMohann** [comment] 2024-07-18 12:21
Hi @davidjgonzalez , I've added the information you asked for. If that's enough, could you please remove the 'need more info' tag? Also, please let us know any possible cause for this issue.

**Comment by RahulMohann** [comment] 2024-07-20 04:17
Hi @davidjgonzalez , 
Thanks for looking into this. One thing I've noticed.

I see there is no file type tagged to your .oft asset. Whereas in our case, it's categorized as 'image/png' in author, when we add the rendition cq5dam.thumbnail.319.319.png  to the asset. Is that what causing our issue?

Otherwise, it's the same. I've attached the screenshots. Can you please check once?

Thanks,
Rahul

**Comment by RahulMohann** [comment] 2024-07-20 04:19
<img width="953" alt="AEM-Rendition" src="https://github.com/user-attachments/assets/4dd6ec93-be80-4715-b1aa-589a2ad0b79e">
<img width="196" alt="AEM-Oft" src="https://github.com/user-attachments/assets/90fb044c-f932-42d4-b720-f4b90cf2447b">
<img width="379" alt="CorruptedOftThumbnail" src="https://github.com/user-attachments/assets/6b8251ce-6836-4660-8ff7-cbdc1b45627d">

**Comment by RahulMohann** [comment] 2024-07-20 04:21
<img width="196" alt="AEM-Oft" src="https://github.com/user-attachments/assets/4baedb26-d5e9-4069-a00b-15068a9ed114">

**Comment by RahulMohann** [comment] 2024-07-20 04:24
<img width="652" alt="AEM-oft-prop" src="https://github.com/user-attachments/assets/61736ffd-47ab-4c19-b50a-4994fc3baa43">

**Comment by davidjgonzalez** [comment] 2024-07-20 13:33
Is that file type metadata field mapped to dc:format?

How is an OFT getting set to an image mime type? Aren't they text files? (Can you post an example OFT file that doesn't contain any sensitive info? Or strip one down?)

Now that you mention this tho - I think I know what's happening. There is logic in ASC to use the high performance dynamic imaging (webp) for thumbnails of image assets .. since oft aren't actually images, when this request is made it fails to return an image. If the asset is not an image, it should fall back to the OOTB thumbnail servlet.

This explains why it works for me (my oft doesn't have a image mine type) but fails for you (you have an image mine type set)

... we should figure out how/why your ofts are getting an incorrect mime type set..

**Comment by RahulMohann** [comment] 2024-07-20 18:38
Hi @davidjgonzalez, I've checked again in our Stage instance, and I see that no file type is getting updated for .oft assets in Stage. But in PROD, it's saved as an image/png. However, in Stage as well, the thumbnail is broken. So I'm confused now if it's because of the wrong file type or something else. It's showing as broken in the author page view as well as published page.
I've attached a sample oft file.

**Comment by RahulMohann** [comment] 2024-07-20 18:39
[newsletter.zip](https://github.com/user-attachments/files/16322015/newsletter.zip)

**Comment by RahulMohann** [comment] 2024-07-20 18:40
It doesn't allow me to attach a .oft file. Hence added it to zip and attached.

**Comment by davidjgonzalez** [comment] 2024-07-22 20:59
@RahulMohann was able to reproduce and fix: https://github.com/adobe/asset-share-commons/pull/1159

**Comment by RahulMohann** [comment] 2024-07-23 10:34
Thanks a lot @davidjgonzalez . When this will be released and which version of ASC?

**Comment by davidjgonzalez** [comment] 2024-07-23 12:33
This will be in 3.8.12 -- Sonatype had errors yesterday, but ii was able to cut a release today! So it should be available in maven central in an hour or two.

**Closed by davidjgonzalez** 2024-07-23 12:33 UTC
Labels: bug

**Comment by RahulMohann** [comment] 2024-07-23 17:09
Hi @davidjgonzalez - I see the .oft files uploaded by users are still getting tagged as image/png to dc:format in AEM. But it doesn't happen for the asset I attached to this ticket. Not sure what's causing it. Any idea how we can stop the asset from getting updated to a particular file type in AEM cloud service?

**Comment by RahulMohann** [comment] 2024-07-23 17:18
Also, to add, I tested the 3.8.12 version in our Dev, and it works fine for the .oft files that aren't tagged as 'IMAGE' in AEM.

**Comment by davidjgonzalez** [comment] 2024-07-23 20:26
👍 thanks for confirming. 

Assets with images i think will still not work correctly (tho i think? they should use the client side fall back -- i need to test that).

It's very strange your OFTs are being set as image/* ... that seems wrong. Do you have a Metadata profile or something doing this? I never saw it happen with vanilla AEM.
