### ISSUE TITLE
Apply the concept of package types by moving items from ui.apps to ui.content

### ISSUE THREAD

**Issue by dominik-lienemann** [adobe/asset-share-commons#408] opened 2019-05-17 08:20 UTC
With https://issues.apache.org/jira/browse/JCRVLT-170, the separation of application and content packages is defined:

- Application Packages only provide content to /apps, /libs
- Content Packages contain the rest

To comply with that, I suggest that the folders /etc, /home and /_oak_index below https://github.com/Adobe-Marketing-Cloud/asset-share-commons/tree/develop/ui.apps/src/main/content/jcr_root are moved to the ui.content package.

See #109  for resources to move.

**Comment by davidjgonzalez** [comment] 2019-05-20 00:47
@dominik-lienemann is this a dupe of https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/109 ?

Alternatively, `ui.content` could be renamed to `ui.sample-content` (or something) since it (ui.content) currently contains a sample build out of ASC which you wouldn't want to deploy to production, and move the conf 'content' from `ui.apps` to `ui.content`

**Comment by dominik-lienemann** [comment] 2019-05-20 06:39
@davidjgonzalez true, #109 triggers a similar change. 

Your proposal of renaming the modules makes sense, then there is no mix between sample content and actual application relevant content.

**Comment by davidjgonzalez** [comment] 2019-05-21 15:11
@dominik-lienemann sounds good - we should follow the conventions of the latest Aem maven archetype (haven't created a new project w/ it since I've been off so don't know if they've changed it)

**Comment by davidjgonzalez** [comment] 2020-02-21 14:45
This split has been merged into develop for ASC v2 release.

**Closed** 2021-04-16 14:15 UTC
Labels: enhancement, pr-merged
