### ISSUE TITLE
Download, Share don't work. AEM Version 6.5.11 ASC Version 2.2.0

### ISSUE THREAD

**Issue by sramvg** [adobe/asset-share-commons#751] opened 2022-06-15 20:00 UTC
**Describe the bug**
Download and Share link don't work in Asset Share Commons publisher instance. Works fine in Author

**Environment**
* AEM Version: ? 6.5.11
* Asset Share Commons Version: ? 2.2.0
* Author, Publish or both? Publisher

**To Reproduce**
1. Go to page created by Asset Detail template
2. Click on 'Download or Share
4. Nothing happens

**Expected behavior**
Expected to Download or Share Modal component show up

**Screenshots**
Attached error log seen
[asc_download_error_publisher_logs.txt](https://github.com/adobe/asset-share-commons/files/8912677/asc_download_error_publisher_logs.txt)
[asc_download_error_publisher_logs.txt](https://github.com/adobe/asset-share-commons/files/8912692/asc_download_error_publisher_logs.txt)

**Comment by davidjgonzalez** [comment] 2022-06-16 18:38
@sramvg  Tested and this works fine on a vanilla 6.5.11 w/ 2.2.0 (you should still upgrade to 2.2.2) ...

![2022-06-16 at 2 36 PM](https://user-images.githubusercontent.com/1451868/174141684-906ce473-72e4-437f-84be-f54a4e86244e.jpg)

I'd check to see if that `path` HTTP POST request parameter is being set, and/or that that path being sent exists as a readable asset in AEM.

Closing for now since i cant reproduce. Please re-open if you can provide more details on how to reproduce the issue.

**Closed by davidjgonzalez** 2022-06-16 18:38 UTC
Labels: bug
